# Generated by Django 3.0.2 on 2020-01-19 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycleissuer', '0004_auto_20200119_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
