# Generated by Django 3.0.2 on 2020-01-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleissuer', '0009_auto_20200122_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
